language: python
sudo: required
python:
  - "3.6"
cache: pip
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install git+git://github.com/pyqtgraph/pyqtgraph.git
  - pip install git+git://github.com/AlexanderSchober/simpleplot_qt.git
  - python setup.py install
script:
  python Test/test.py
