sudo: required
matrix:
    include:
        - os: linux
          language: python
          python: 3.6
        # - os: osx
        #   language: python
        #   python: 3.6

cache: pip
before_install:
  - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install git+git://github.com/pyqtgraph/pyqtgraph.git
  - pip3 install git+git://github.com/AlexanderSchober/simpleplot_qt.git
  - python setup.py install
  
script: python -m unittest
after_success:
  - coveralls