sudo: required
matrix:
    include:
      - os: linux
        language: python
        python: 3.6
        addons:
          apt:
          sources:
            - sourceline: "deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe"
          packages:
            - xvfb
      - os: osx
        language: generic
        env: PYTHON=3.6
cache: pip
before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install openssl readline && brew outdated pyenv || brew upgrade pyenv && brew install pyenv-virtualenv && pyenv install $PYTHON && export PYENV_VERSION=$PYTHON && export PATH="/Users/travis/.pyenv/shims:${PATH}" && pyenv-virtualenv venv && source venv/bin/activate && python --version;
  elif [ "$TRAVIS_OS_NAME" == "linux" ]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start ;
  fi

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install git+git://github.com/pyqtgraph/pyqtgraph.git
  - pip3 install git+git://github.com/AlexanderSchober/simpleplot_qt.git
  - python setup.py install
  
script: python -m unittest -v

notifications:
  email: false