sudo: required
dist: trusty
matrix:
    include:
      - os: linux
        language: python
        python: 3.6

before_install: 
  - sudo apt-get -y install qt53svg qt53base qt53tools qt53declarative libsndfile1-dev librtlsdr-dev librtlsdr0 libfftw3-dev portaudio19-dev libfaad-dev zlib1g-dev rtl-sdr libusb-1.0-0-dev mesa-common-dev libgl1-mesa-dev libqt4-opengl-dev libsamplerate-dev
  - source /opt/qt53/bin/qt53-env.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start 
install:

  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install git+git://github.com/pyqtgraph/pyqtgraph.git
  - pip3 install git+git://github.com/AlexanderSchober/simpleplot_qt.git
  - python setup.py install
  
script: python -m unittest -v

notifications:
  email: false